spring:
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "neuronalnetworks"
      username: "admin"
      password: "password"
      authentication-database: "admin"

server:
  port: "8082"

app:
  security:
    disable: true
