spring:
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "neuronalnetworks"
      username: "admin"
      password: "password"
      authentication-database: "admin"

server:
  port: "8082"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /network-docs

app:
  security:
    disable: true
    public-key: "./NeuronalNetworks/src/main/resources/keys/keycloak.pub"

